version: 2.1
orbs:
    node: circleci/node@3.0.0
    slack: circleci/slack@3.4.2
    cypress: cypress-io/cypress@1
jobs:
    build-test-and-notify:
        executor:
            name: node/default
        steps:
            - checkout
            - run:
                  name: Install dependencies
                  command: npm install
            - run:
                  name: "Unit Test"
                  command: npm test --collectCoverage=true --silent
            - store_artifacts:
                  path: coverage
            - slack/notify:
                  color: "#42e2f4"
                  mentions: "channel"
                  message: "Build triggered by ${CIRCLE_USERNAME} on branch ${CIRCLE_BRANCH}"
            - slack/status:
                  fail_only: false
                  mentions: "channel"
workflows:
    build:
        jobs:
            - cypress/run:
                  yarn: true
                  start: yarn build && yarn next start
                  wait-on: "http://localhost:3000"
            - build-test-and-notify
