version: 2.1
orbs:
  node: circleci/node@3.0.0
  slack: circleci/slack@3.4.2
  cypress: cypress-io/cypress@1
jobs:
  build-test-and-notify:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run: npm test
      - slack/notify:
          color: "#42e2f4"
          mentions: "channel"
          message: "Build triggered by ${CIRCLE_USERNAME} on branch ${CIRCLE_BRANCH}"
      - slack/status:
          fail_only: false
          mentions: "channel"
workflows:
  build:
    jobs:
      - cypress/run:
          yarn: true
          start: yarn build && yarn next start
      - build-test-and-notify
          
