version: 2.1
orbs:
    node: circleci/node@4.1.0
jobs:
    build-test-and-notify:
        executor:
            name: node/default
        steps:
            - checkout
            - run:
                  name: Install dependencies
                  command: npm install
            - run:
                  name: "Unit Test"
                  command: npm test --collectCoverage=true --max-workers=1
                  environment:
                      NODE_OPTIONS: --max_old_space_size=8192
            - store_artifacts:
                  path: coverage
workflows:
    build:
        jobs:
            - build-test-and-notify
