#!/bin/sh
# husky

# Created by Husky v4.3.0 (https://github.com/typicode/husky#readme)
#   At: 9/19/2020, 1:03:52 PM
#   From: /Users/katebrune/Documents/code/projects/moodqueue/node_modules/husky (https://github.com/typicode/husky#readme)

. "$(dirname "$0")/husky.sh"
